version: 2
jobs:
  build:
    docker:
      - image: andrewlock/dotnet-mono

    steps:
      - checkout
      - run:
          name: push-docker
          command: |
            chmod 755 ./*.sh
            export TERM=xterm-256color
            ./fake.sh build